listen_addresses = ['0.0.0.0:53', '[::1]:53']
max_clients = 250

[ipv4_servers]
# Whether or not to use DNSCrypt servers reachable over IPv4
use_ipv4 = true

[ipv6_servers]
# Whether or not to use DNSCrypt servers reachable over IPv6
use_ipv6 = true

[dnscrypt_servers]
# Whether or not to use DNSCrypt servers
use_dnscrypt = true

[doh_servers]
# Whether or not to use DNS-over-HTTP/2 servers
use_doh = false

require_dnssec = false
require_nolog = true
require_nofilter = true
force_tcp = false
timeout = 2500
keepalive = 30

[proxy]
# HTTP/HTTPS/SOCKS proxy
# proxy = 'socks5://127.0.0.1:9050'

[public_resolvers]
# URL of the public-resolvers.md file
resolvers_list = 'public-resolvers.md'

[sources]
# Remote lists of DNS servers
'public-resolvers' = ['https://download.dnscrypt.info/resolvers-list/v2/public-resolvers.md', 'minisign:RWQf6LRCGA9i53mlYecO4IzT51TGPpvWucNSCh1CBM0QTaLn73Y7GFO3']
