---
version: '3.7'

networks:
  ip6net:
    external: true

services:
  wireguard:
    image: lscr.io/linuxserver/wireguard:latest
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    privileged: true
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Etc/UTC
      SERVERURL: vpn.roshamagin.site
      SERVERPORT: 63247
      PEERS: 1
      PEERDNS: auto
      INTERNAL_SUBNET: 10.13.13.0/24,fd42:42:42::0/64
      ALLOWEDIPS: 0.0.0.0/0, ::0/0
      PERSISTENTKEEPALIVE_PEERS: 25
      LOG_CONFS: "true"
    volumes:
      - ./config:/config
      - /lib/modules:/lib/modules #optional
    ports:
      - 63247:51820/udp
    sysctls:
       net.ipv4.conf.all.src_valid_mark: 1
       net.ipv6.conf.all.forwarding: 1
    networks:
      - ip6net