---
version: '3.7'

networks:
  wireguard:
    enable_ipv6: true

services:
  wireguard:
    image: lscr.io/linuxserver/wireguard:latest
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Etc/UTC
      SERVERURL: vpn.roshamagin.site
      SERVERPORT: 63247
      PEERS: 1
      PEERDNS: 1.1.1.1
      INTERNAL_SUBNET: 10.13.13.0
      ALLOWEDIPS: 0.0.0.0/0
      PERSISTENTKEEPALIVE_PEERS: 25
      LOG_CONFS: "true"
    volumes:
      - ./config:/config
      - /lib/modules:/lib/modules #optional
    ports:
      - 63247:51820/udp
    sysctls:
       net.ipv4.conf.all.src_valid_mark: 1
    restart: unless-stopped
    networks:
      ipv6_net:

networks:
  ipv6_net:
    driver: overlay
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 2001:470:1f08:27::/64