version: '3.8'

services:

  traefik:
    image: traefik:latest
    command:
      - --providers.docker=true
      - --providers.docker.swarmMode=true
      - --providers.docker.endpoint=unix:///var/run/docker.sock
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --certificatesresolvers.myresolver.acme.dnschallenge=true
      - --certificatesresolvers.myresolver.acme.dnschallenge.provider=cloudflare
      - --certificatesresolvers.myresolver.acme.email=info@roshamagin.site
      - --certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json
    environment:
      - CF_DNS_API_TOKEN=$CF_API_KEY
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /mnt/glusterfs/letsencrypt:/letsencrypt
    networks:
      - postgres-network
    deploy:
      labels:
        - traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https
      placement:
        constraints:
          - node.role == manager

networks:
  public:
    external: true
  galera_galera-network:
    external: true

volumes:
  content:
    driver: local