---
version: '3.7'

networks:
  ip6net:
    name: ip6net
    enable_ipv6: true
    attachable: true
    ipam:
      config:
        - subnet: 172.19.0.0/16
          gateway: 172.19.0.1
        - subnet: 2001:db8::a:71a5/125
          gateway: 2001:db8::a:71a5:1

services:
  wireguard:
    image: ghcr.io/romaxa55/vpn_wireguard_docker/wireguard:1.0.3
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Etc/UTC
      SERVERURL: vpn.roshamagin.site
      SERVERPORT: 63247
      PEERS: 0
      PEERDNS: "dnscrypt_proxy"
      INTERNAL_SUBNET: 10.13.13.0/24,fd42:42:42::0/64
      ALLOWEDIPS: 10.13.13.0/24, fd42:42:42::0/64
      PERSISTENTKEEPALIVE_PEERS: 25
      LOG_CONFS: "true"
    volumes:
      - ./config:/config
      - /lib/modules:/lib/modules #optional
    ports:
      - 63247:63247/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.forwarding=1
      - net.ipv6.conf.all.disable_ipv6=0
    networks:
      - ip6net