version: "3.8"

services:
  dnscrypt_init: &dnscrypt_base
    image: zquestz/dnscrypt-server:latest
    restart: always
    volumes:
      - keys:/opt/encrypted-dns/etc/keys
    environment:
      - TZ='UTC'
    command: "init -N dns.roshamagin.site -E '127.0.0.1:5443'"
    container_name: dnscrypt_init

  dnscrypt_server:
    <<: *dnscrypt_base
    command: "start"
    container_name: dnscrypt_server

  dnscrypt_proxy:
    image: klutchell/dnscrypt-proxy
    container_name: dnscrypt_proxy
    volumes:
      - ./config:/config
    restart: always
    depends_on:
      - dnscrypt_start
volumes:
  keys:
