---
version: '3.7'

networks:
  ip6net:
    external: true

services:
  wireguard:
    image: ghcr.io/romaxa55/vpn_wireguard_docker/wireguard:master
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Etc/UTC
      SERVERURL: vpn.roshamagin.site
      SERVERPORT: 63247
      PEERS: 0
      PEERDNS: 8.8.8.8, 8.8.4.4, 2001:4860:4860::8888, 2001:4860:4860::8844
      INTERNAL_SUBNET: 10.13.13.0/24,fd42:42:42::0/64
      ALLOWEDIPS: 10.13.13.0/24, fd42:42:42::0/64
      PERSISTENTKEEPALIVE_PEERS: 25
      LOG_CONFS: "true"
    volumes:
      - ./config:/config
      - /lib/modules:/lib/modules #optional
    ports:
      - 63247:63247/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.forwarding=1
      - net.ipv6.conf.all.disable_ipv6=0
    networks:
      - ip6net