---
version: '3.7'

services:
  wireguard:
    image: ghcr.io/romaxa55/vpn_wireguard_docker/wireguard:1.0.3
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Etc/UTC
      SERVERURL: vpn.roshamagin.site
      SERVERPORT: 63247
      PEERS: 0
      PEERDNS: "dnscrypt_proxy"
      INTERNAL_SUBNET: 10.13.13.0/24,fd42:42:42::0/64
      ALLOWEDIPS: 10.13.13.0/24, fd42:42:42::0/64
      PERSISTENTKEEPALIVE_PEERS: 25
      LOG_CONFS: "true"
    volumes:
      - ./config:/config
      - /lib/modules:/lib/modules #optional
    ports:
      - 63247:63247/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.forwarding=1
      - net.ipv6.conf.all.disable_ipv6=0
    networks:
       ip6net:
        ipv4_address: 172.19.0.10
        ipv6_address: 2001:db8::a:71a5:10

  dnscrypt_proxy:
    image: klutchell/dnscrypt-proxy
    container_name: dnscrypt_proxy
    volumes:
      - ./config/dnscrypt-proxy.toml:/config/dnscrypt-proxy.toml
    restart: always
    ports:
      - 53:53/tcp
      - 53:53/udp
    depends_on:
      - wireguard
    networks:
       ip6net:
          ipv4_address: 172.19.0.100
          ipv6_address: 2001:db8::a:71a5:100

  adguard:
    image: adguard/adguardhome
    container_name: adguardhome
    networks:
       ip6net:
          ipv4_address: 172.19.0.53
          ipv6_address: 2001:db8::a:71a5:53
       public:
    volumes:
      - ./config/work:/opt/adguardhome/work
      - ./config/adguard/conf:/opt/adguardhome/conf
    labels:
        - traefik.enable=true
        - traefik.http.routers.adguard.tls=true
        - traefik.http.routers.adguard.rule=Host(`adguard.vpn.roshamagin.site`)
        - traefik.http.routers.adguard.entrypoints=websecure
        - traefik.http.routers.adguard.tls.certresolver=myresolver
        - traefik.http.services.adguard.loadbalancer.server.port=3000


volumes:
  keys:

networks:
  public:
    external: true
  ip6net:
    name: ip6net
    enable_ipv6: true
    attachable: true
    ipam:
      config:
        - subnet: 172.19.0.0/16
          gateway: 172.19.0.1
        - subnet: 2001:db8::a:71a5/64
          gateway: 2001:db8::a:71a5:1