---
version: '3.7'

services:
  wireguard:
    image: lscr.io/linuxserver/wireguard:latest
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Etc/UTC
      SERVERURL: vpn.roshamagin.site
      SERVERPORT: 63247
      PEERS: 1
      PEERDNS: 1.1.1.1
      INTERNAL_SUBNET: 10.13.13.0/24
      ALLOWEDIPS: 0.0.0.0/0
      PERSISTENTKEEPALIVE_PEERS: 25
      LOG_CONFS: "true"
    volumes:
      - ./config:/config
      - /lib/modules:/lib/modules #optional
    ports:
      - 63247:51820/udp
    deploy:
      mode: global
    ports:
    - target: 51820
      published: 63247
      protocol: "udp"
      mode: "host"

