version: "3"
services:
  dnscrypt:
    image: zquestz/dnscrypt-server:latest
    container_name: dnscrypt
    restart: always
    command: "init -N dns.roshamagin.site -E '127.0.0.1:5443'"
    #command: "start"
    volumes:
      - keys:/opt/encrypted-dns/etc/keys
    environment:
    - TZ='UTC'

volumes:
  keys:
