---
all:
  children:
    vpn:
      hosts:
        VPN-Norway:
          ansible_host: 88.201.245.193
          ansible_user: "{{ ssh_user }}" # User firt time user root
          ansible_port: "{{ security_ssh_port }}" # port 22
